#!/bin/bash
_where_am_i="$(dirname "$([[ -h "$0" ]]&&readlink $0||which $0)" 2> /dev/null)"
if [[ -z "${_where_am_i}" ]]; then
	_where_am_i="$(dirname $0)"
fi

# to combine to one script, replace code below with enco.src code
_src_file="${_where_am_i}/enco.src"
if [[ -f "${_src_file}" ]]; then
	source "${_src_file}"
else
	echo "   Source file \"${_src_file}\" dose not exist."
	exit 1
fi
# to combine to one script, replace code above with enco.src code

DST_CHARSET="gb18030"
SRC_CHARSET="utf8"

#main begin
echo
if [[ ! $1 ]]; then
	_usage
fi

_convert $@
echo
